P403n1x87/austin

ChangeLog
README.md
configure.ac
src/Makefile.am
src/austin.c
src/austin.h
src/mem.h
src/py_code.c
src/py_frame.c
src/py_proc.c
src/py_proc.h
src/py_thread.c
src/python.h
src/version.c
src/version.h

Introduced support for multiple versions of Python 3 on amd64 Linux. Given the positive test results with Python 3.6 on Windows 10 via WSL, there are good chances that the same support extends to Windows too.
Regarding the design of the solution, two possibilities have been considered. One was to make every unit of code aware of the Python version detected and then decide on the data structure to use accordingly. The second approach, which is the one adopted for the change, was to centralise all the versioning information in a dedicated unit and have any other unit that is affected by differences among versions refer to a single global variable.
There are no known regressions. The version inference has been changed from the rodata scan to a popen on the executable with the `--version` …

Support multiple Python 3 versions on amd64 Linux

---

ChangeLog
README.md
configure.ac
src/austin.h
src/py_proc.c
src/py_proc.h

This is a follow-up bugfix for #2.
N.A.
N.A.
The bugfix has been tested with Bash test cases for BATS on an Ubuntu base image (18.04.1) with all the interpreters installed from [deadsnakes](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa).
These will be added later on and will possibly be run by Travis after the build process.

Bugfix: Austin can now attach again to a running Python process.

---

README.md
src/argparse.c
src/argparse.h
src/linux/py_proc.h
src/mem.h
src/py_proc.c
src/stats.c
test/target34.py
test/test_attach.bats
test/test_fork.bats
test/test_valgrind.bats

This change introduces the timeout option to adjust the wait timeout when searching for a valid Python interpreter state at start up. This could be useful on slow machines, where Python start up could be slower than the default timeout, e.g. on Travis CI containers.
_En passant_, the symbol resolution on Linux has been enhanced by correcting the virtual addresses in the ASLR case.
N. A.
This change introduces a slightly new and improved behaviour on Linux systems. There still are some versions of Python for which the symbols cannot be resolved, even after the correction for ASLR. There is a margin of risk that the corrected address might point to a false interpreter state that could stall Austin.
The current test suite. Re-enabled tests for Python 2.3, but disabled those for Python 2.4 on …

Introduce timeout command-line option

---

.travis.yml

Create binary releases on GitHub directly from Travis-CI
N.A.
Build jobs could fail as the deployment process has not been tested before integration into master
N. A.

Add GitHub Releases support

---

src/austin.c
src/py_proc.c
src/py_proc.h
src/version.c
test/test_attach.bats
test/test_fork.bats
test/test_valgrind.bats

The offset of the _PyRuntime.gilstate.tstate_current field varies across Python patch releases and therefore needs to be determined at runtime. This affects the new memory profiling mode.
Given the granularity on minor releases of the versioning support built into Austin, the offset cannot be hard-coded and therefore needs to be determined at runtime.
The bug affects the new memory profiling mode. When sampling at low frequencies, more samples than initially anticipated could be lost while Austin tries to determine the offset of the _PyRuntime.gilstate.tstate_current field.
Standard test suite.

Fix current thread de-referencing in Python 3.7+

---

.travis.yml
src/austin.c
src/linux/py_proc.h
src/stats.c
src/stats.h

The parser of the maps file on Linux is broken on WSL. We bite the 
bullet and use `sscanf` to thoroughly parse the maps file.
Also fixed the reporting of bad samples in the stats.
Small fix; no alternative designs required.
Non expected.
The existing test suite.

Fix Austin on WSL failing to find BSS section from maps file.

---

src/Makefile.am
src/argparse.c
src/argparse.h
src/austin.c
src/linux/py_proc.h
src/logging.h
src/mac/py_proc.h
src/py_proc.c
src/py_proc.h
src/py_proc_list.c
src/py_proc_list.h
src/py_thread.c
src/py_thread.h
src/win/py_proc.h
test/target.py
test/target34.py
test/target_mp.py
test/test.bats
test/test_attach.bats
test/test_fork_mp.bats

Created a new module to handle a list of Python processes that are  descendant
of the given command or the attached process. At every  iteration, every valid
running process in the list is sampled.
The new mode can be turned on with the new `-C` or `--children` options. In this
case, the output will contain the process identifier as the first fragment in
each collected sample.
The test suite has been extended to test multi-process support when  starting a
new multi-process Python program.
The code has been refactored. In particular the sample output generation  has
been moved in py_thread.c and the higher level sampling logic in  py_proc.c.
This allows the new data structure to easily call on these  methods.
As for the PID table generation logic on Linux, this has been modelled on the …

Add multi-process support

---

.travis.yml
src/python.h
src/version.c
test/test_attach.bats
test/test_fork.bats
test/test_fork_mp.bats
test/test_valgrind.bats

Added support for the CPython 3.8 API.
N. A.
None expected
The existing test suite, which has been extended to cover CPython 3.8

Add support for Python 3.8

---

src/Makefile.am
src/austin.c
src/linux/py_proc.h
src/py_proc.c
src/py_proc_list.c

In order to avoid zombie processes, a thread is required on Linux that 
waits the forked child process. This way it is terminated correctly 
instead of being reported as still running.
N. A.
None expected.
The existing test suite.

Fix py_proc__wait on Linux

---

.travis.yml
src/mac/py_proc.h
test/macos/test.bats
test/macos/test_attach.bats
test/macos/test_fork.bats
test/macos/test_fork_mp.bats
test/macos/test_valgrind.bats

The test suite has been enlarged to include test cases for Mac OS to run with bats-core. The Linux tests form the basis on top of which the new tests build. However, only the Python versions from Homebrew and the Anaconda cask are tested. They provide examples of distributions respectively with and without a shared library. Valgrind tests seemed to report false problems so they are being skipped at the moment.
No alternative design considered.
None expected
The new test suite.

Add Mac OS tests

---

.travis.yml
choco/austin.nuspec
choco/tools/chocolateyinstall.ps1
wix/Austin.wxs

Automate the generation of the MSI installer with Travis by installing 
the wixtoolset and building the installer. After deployment to GitHub 
Releases, we try to package the project and deploy to Chocolatey.
N. A.
Deployment won't be tested until this PR is merged. There is a risk that the Travis job will fail when it comes to this phase.
N. A.

Deploy MSI installer to GitHub and nupkg to Chocolatey

---

README.md

The link in the readme.md file for speedscope implicitly points to a file within the repository (`https://github.com/P403n1x87/austin/blob/master/speedscope.app`).
Obviously, this file does not exist, as the correct link should be https://speedscope.app.
Without the protocol prefix, Github seems unable to render this link correctly.
Click on the link ...

[minor] Fix speedscope links

---

src/argparse.c

As I mentioned prior to the 2.1.0 release, the name of this function prevents compiling on many unix systems including OS/X
https://github.com/P403n1x87/austin/issues/65#issuecomment-750945043  However the issue remains in 2.1.0
This is because the system headers define a function called `strtonum()`, for example: https://illumos.org/man/3c/strtonum
Just renaming this function solves the problem.

Fix symbol name clash on BSD systems with strtonum()

---

src/argparse.c
src/austin.c
src/hints.h
src/mac/py_thread.h
src/py_proc.c
src/py_thread.c
src/py_thread.h
test/macos/test.bats
test/macos/test_sleepless.bats

The initial implementation of the sleepless mode was not particularly useful. With this change, sleepless mode can be used to estimate CPU time on macOS by filtering out samples collected while a thread is not running.
The macOS API actually offers a bit more than just the thread status, namely both user and system time for each thread. This implementation only reports the thread status and uses the real clock to give an estimate of CPU time.
Anybody relying on the old semantics for the sleepless mode should be aware of this breaking change.
Added a test case to check that no idle frames are emitted while an idle thread is being sampled.

feat(mac)!: use sleepless mode to estimate CPU time

---

README.md

Fix link to austin-python repository

---

ChangeLog
src/linux/py_thread.h

Older versions of glibc have a different struct pthread definition that requires scanning the pthread buffer with smaller steps in order to find the actual offset.
Mitigates #93. A cleaner fix will be provided by #95.
An alternative and cleaner fix is described in the comments to #95. The currently proposed fix is just mitigation.
None expected.
The existing test suite.

fix(linux): fall-back inference of TID offset

---

.github/workflows/dev_release.yml
.github/workflows/dev_release_arch.yml
.github/workflows/release.yml
.github/workflows/release_arch.yml
README.md
src/argparse.c
src/austin.c
src/linux/addr2line.h
src/linux/py_proc.h
src/linux/vm-range-tree.h
src/py_proc.c
src/py_proc.h
src/py_thread.c
utils/resolve.py

Implemented a stripped-down version of the addr2line utility to resolve the source file and line number of native stacks in where mode. Normal sampling mode does not benefit from this to ensure the best sample throughput.
Also ensure that we retry initialising the unwind cursor in case of an expected error code, to prevent skipping samples.
Manually parsing the DWARF information is an alternative design, but the effort would be much larger.
None expected

feat(austinp): resolve native stacks

---

.github/workflows/checks.yml
README.md
scripts/cog.sh
src/argparse.c

Use cog to autogenerate the content of some sources to ensure they
are up-to-date with the latest changes.
N. A.
N. A.
New CI job to run cog checks.

ci: add cog support and checks

---

.github/workflows/checks.yml
.github/workflows/tests.yml
test/__init__.py
test/test_attach.py
test/utils.py

With this change, we can use the install-python action for installing Python on all supported platforms.

ci: use matrix for Python versions

---

.github/workflows/checks.yml
.github/workflows/tests.yml

This PR ensures that checks and tests run on PRs

ci: run checks and tests on PRs

---

ChangeLog
README.md
src/logging.c
test/test_fork.py

Add a check in logging.c for the environment variable AUSTIN_NO_LOGGING. If it is nonempty, logging is disabled on all platforms.
None considered.
No possible side-effects, as the odds of existing users inadvertently setting AUSTIN_NO_LOGGING are minimal.
To test (on Linux):
1. Compile with `gcc -O3 -Os -Wall -pthread src/*.c -o src/austin`
2. Open a separate terminal to watch the syslog output with `journalctl -f -t austin -n0`
3. Run `AUSTIN_NO_LOGGING=1 ./src/austin python3 -c 'import time; time.sleep(1)'` and observe that nothing is output to syslog
4. Run `AUSTIN_NO_LOGGING= ./src/austin python3 -c 'import time; time.sleep(1)'` and observe the usual output to syslog
5. Run `./src/austin python3 -c 'import time; time.sleep(1)'` and observe the usual output to syslog

Allow disabling logging by setting AUSTIN_NO_LOGGING in the environment

---

.github/workflows/tests.yml
README.md

This PR implements a workaround for the latest release of Python on MacOS to allow the tests to work in CI. The setup-python GitHub Action has started using the official Python installer on MacOS runners, that comes with the Hardened Runtime enabled. Removing the signature from the binaries allows Austin to work with them, thus allowing the CI job to work. This can also be used by Austin users as a workaround, and mentions of this have been added to the documentation.
The signing of the Austin binary with Debugging Tools Entitlements might have provided an alternative, but it requires more effort to get it to work.
N.A.

ci: hardened runtime workaround

---

.github/workflows/tests.yml
test/cunit/__init__.py
test/cunit/test_cache.py
test/utils.py

Depending on how Python is compiled on certain architectures, not giving types to C functions using `ctypes` can lead to mangled values (e.g. a 64-bit pointer having its top 32 bits set to 1). This is a highly likely source of segmentation faults, and they were discovered using the Python builds from the setup-python action.
With this change, we ensure that all arguments and return values get a default type. We use `c_void_p` for any pointer and `c_long` for any non-pointer argument/return value, to ensure that the passed bits are not altered by unwanted conversions.
N. A.
N. A.

ci(cunit): set generic argument and return types

---

ChangeLog
src/austin.c
src/cache.c
src/cache.h
src/events.h
src/hints.h
src/mojo.h
src/py_proc.c
src/py_proc.h
src/py_thread.c
src/py_thread.h
src/stack.h
utils/mojo2austin.py

Some strings may be shared across code objects and therefore it makes sense to store them in a cache for faster access.
N.A.
We expect string objects attached to code objects to live as long as the latter so that addresses are not reused for different string objects.

perf: cache string objects

---

configure.ac

Fill out the template below. Any pull request that does not include enough
information to be reviewed in a timely manner may be closed at the maintainers'
discretion.

ci(austinp): link libbfd statically

---

.github/workflows/tests.yml
src/Makefile.am

Catch potential issues during compilation by forcing workflows to fail on compilation warnings.
N.A.
N.A.

ci: turn compilation warnings into errors

---

ChangeLog
configure.ac
snap/snapcraft.yaml
src/austin.h
src/cache.c
src/cache.h
src/mojo.h
src/py_proc.c
src/py_proc.h
src/py_thread.c
src/py_thread.h
src/stack.h
test/cunit/test_cache.py
test/test_fork.py

This change fixes issues with the MOJO format that mostly arise in multiprocess applications and when there is a considerable number of strings and frames. We move to an expandable string cache and better MOJO references in events.
We could have stored the string key on the frame object. On the one hand, this allows for fixed-size string caches, but on the other, it would require two cache lookups whenever a frame is retrieved from the frame cache.
None expected. The only concern is a potential memory usage increase, but it is bounded by a factor of the total memory used by Python code objects from the running process(es).
Added MOJO variant to the multiprocess fork tests.

fix(mojo): use string key for ref and more bytes for frame refs

---

.github/workflows/checks.yml

The use of the setup-python action should speed up the coverage run and introduce the dev sources with no extra dependencies.

checks: add dev dependency to coverage

---

ChangeLog
src/py_proc.c

When trying to profile a child process that is not recognised as a Python process, Austin tries to resolve the interpreter state too many times, causing poor overall performance. This change ensures that if we fail to attach to a child Process we give up quickly to allow for samples to be collected efficiently for the processes that are correctly identified as Python processes.
None considered
None expected, based on the current test suite
The issue was brought to light by uWSGI support tests. Those will be added in a separate PR.

fix: multiprocess fail-fast

---

.github/workflows/build_arch.yml
.github/workflows/release_arch.yml
scripts/build_arch.sh

The architectures build and release workflow share the same build script. This has been factored out into a script to reduce duplication and improve maintenance.

ci(arch): factor out build script

---

scripts/benchmark.py
src/cache.c
src/cache.h
src/py_proc_list.c
src/py_proc_list.h
test/cunit/test_cache.py
test/targets/target_mp.py

We use a hash lookup structure instead of plain lookup arrays in multiprocessing support to reduce the overall memory requirements for Austin when sampling child processes.
n/a
None expected
Existing test suite. Added a multiprocess benchmark scenario to monitor performance changes across releases.

perf: use hash lookup in multiprocess support

---

ChangeLog
src/argparse.c
src/linux/py_proc.h
src/py_proc.c
test/test_attach.py
test/utils.py

This change improves the way the VM map of the tracee are parsed on Linux, which allows for better detection of executable  and Python library files. Furthermore, the BSS scan fallback is now more reliable since its location is inferred from the maps too when the binary files are not available from the FS (e.g. when targeting processes spawned from within a chroot jail). This means that we can allow for scenarios like those of #159.
Resolves #159.
Since the section headers are not loaded into memory, we have no viable alternatives but to keep parsing the ELF file for the most accurate information.
There is a chance that some Python distributions on Linux that used to work might no longer work. In fact, we expect the opposite to happen, that is more Python distros and Python-based tools to …

chore(linux): better Python detection

---

src/linux/py_proc.h
src/py_proc.c
test/test_attach.py
test/utils.py

This change allows Austin to infer the PID of a process running in a different PID namespace (e.g. containers) so that the pthread TID field offset can be computed reliably in this case. Previously, the inference would fail and cause an infinite loop.
Resolves #159.
To the best of our knowledge, `/proc/<pid>/status` is the only procfs file that can provide the necessary information to find other PIDs a process is known by.
None expected. This is an enhancement.

chore(linux): infer PID namespace PID

---

.github/workflows/checks.yml
src/austin.c
src/frame.h
src/hints.h
src/linux/py_proc.h
src/linux/py_thread.h
src/mac/py_proc.h
src/mac/py_thread.h
src/py_proc.c
src/py_proc_list.c
src/py_proc_list.h
src/resources.h
src/win/py_proc.h

GCC provides the cleanup attribute which can be used to run a cleanup function when an auto function local variables goes out of scope. We make use of this to refactor and simplify the code in places where resources are used locally but not returned to the caller.
No known alternatives.
None expected.

refactor: use cleanup attribute to handle resources

---

src/linux/common.h
src/linux/py_proc.h
src/py_proc_list.c
src/py_thread.c

A previous change has introduced a helper to open PID-based files from procfs. This change makes use of the helper in other places too for code reuse.
N.A.
None expected

refactor(linux): use the procfs helper

---

.github/workflows/checks.yml
ChangeLog
README.md
src/frame.h
src/linux/addr2line.h
src/mojo.h
src/py_thread.c
test/.flake8
test/requirements.txt
test/targets/column.py
test/test_mojo.py

This change adds support for the extra column-level information exported by the location table of Python 3.11 code objects. The finer-grained location data is made available though the MOJO binary format only.
N.A.
None expected.
Added and extra test case to validate the presence of the extra column-level location data.

feat: support column-level location information

---

.github/workflows/tests.yml

Factor out the build process from the test jobs and make them a prerequisite for actually running the tests. This prevents spawning unnecessary jobs if a compilation error occurs. This also allows adding more compilation scenarios, like the clang one for macOS, to catch potential issues like the one that prevented 3.4.1 to build on conda (see. conda-forge/austin-feedstock#21).

ci: create prerequisite build jobs

---

.github/workflows/benchmarks.yml
scripts/benchmark.py
scripts/requirements-bm.txt
test/utils.py

This change improves the report from benchmark runs by adding t-tests for each scenario. This allows the benchmarks to provide a summary at the end with the scenarios likely to show performance differences between the latest released version and the one that comes with the PR the benchmarks run for.
This also updates the versions being benchmarked to include the latest releases.

ci(benchmarks): improve benchmark reporting

---

.github/workflows/tests.yml
scripts/benchmark.py
scripts/common.py
scripts/requirements-val.txt
scripts/validation.py
test/utils.py

This change implements the ideas set out in https://arxiv.org/abs/2301.08941 to perform a statistical comparison of the flame graphs generated by the latest release and the proposed changes in a PR. The aim is to check whether the statistical data generated by two different versions of Austin come from the same distribution. If this is the case we assume that the two versions generate statistically equivalent data.

ci: add data validation workflow

---

.github/workflows/build_arch.yml
.github/workflows/release.yml
.github/workflows/release_arch.yml
.github/workflows/tests.yml
README.md
scripts/build-wheel.py
scripts/build_arch.sh
scripts/requirements-bw.txt

This change adds extra steps to the CI workflows to build Python wheels so that the Austin binary can be installed with pip from PyPI.

ci: build Python wheels

---

.github/workflows/benchmarks.yml
.github/workflows/checks.yml
.github/workflows/tests.yml

APT repository changes might require `apt-get update` to be called before `apt-get install`.

ci(ubuntu): update before install

---

src/linux/addr2line.h
src/py_proc_list.c

Fill out the template below. Any pull request that does not include enough
information to be reviewed in a timely manner may be closed at the maintainers'
discretion.
Reduce scope of alloc variable
N/A
N/A

chore: minor compilation fixes with gcc 11.3

---

.github/workflows/checks.yml
src/mac/py_proc.h

The version of cppcheck available from the package manager tends to be outdated. In this change we build from sources instead. We cache the build result for faster execution.

ci(checks): build cppcheck from sources

---

src/frame.h
src/py_thread.c

Use the more correct expression for computing the lasti index with Python 3.11.
N. A.
None. We expect compiler optimisations to do a good job with divisions by powers of 2.

refactor: use proper lasti formula for 3.11 

---

.github/workflows/tests.yml
src/austin.c
test/test_cli.py

This change ensures that Austin reports the expected error code and message when running without the superuser privileges.
Fill out the template below. Any pull request that does not include enough
information to be reviewed in a timely manner may be closed at the maintainers'
discretion.

fix(macos): report permission error if not root

---

src/python/symbols.h
test/test_pipe.py

The wrong symbol name was being used on OSX, preventing the inference of the Python version from symbols.
None expected
Added a new test case to check that we get the correct full version from symbols.

fix: version detection on Python 3.11

---

test/requirements.txt
test/support/requirements-uwsgi.txt
test/support/test_uwsgi.py

We run the uwsgi tests in separated virtual environment to ensure that we install it using the interpreter that Austin is being tested against. Currently, we install the dependency in the environment used to run pytest, which means that we test uwsgi with the same Python version in every job.
We make the uwsgi tests run as expected, so there is always the chance of new CI findings.

tests: run uwsgi tests in virtual environment

---

.github/workflows/benchmarks.yml
.github/workflows/build_arch.yml
.github/workflows/checks.yml
.github/workflows/docker.yml
.github/workflows/pre_release.yml
.github/workflows/pre_release_arch.yml
.github/workflows/release.yml
.github/workflows/release_arch.yml
.github/workflows/tests.yml

We bump the checkout action version from 2 to 3, and setup-python from 2 to 4 (the latest at the time this change is being made) to resolve the node12 deprecation warnings.

ci: bump GitHub action versions

---

.github/workflows/benchmarks.yml
.github/workflows/build_arch.yml
.github/workflows/tests.yml

We add path filtering to some GitHub workflows so that they are triggered when necessary.

ci: run certain workflows when necessary

---

.github/workflows/checks.yml
.github/workflows/tests.yml
test/cunit/conftest.py
test/utils.py

We try to collect core dump on Linux once more

ci(linux): collect core dumps

---

.github/workflows/checks.yml
.github/workflows/tests.yml
doc/cheatsheet.svg
scripts/build-wheel.py
src/argparse.c
src/py_proc.c
src/py_string.h
src/py_thread.c
src/py_thread.h
src/python/cframe.h
src/python/code.h
src/python/gc.h
src/python/gil.h
src/python/iframe.h
src/python/interp.h
src/python/runtime.h
src/python/string.h
src/python/thread.h
src/version.h
test/__init__.py

Add support for Python 3.12
Non expected

feat: add support for Python 3.12

---

.github/workflows/tests.yml
src/logging.c
test/utils.py

We add more details to the logs generated by Austin on Windows to include a timestamp and process information. This allows us to collect the data in tests for helping with investigations.
In order to easily get access to the data in CI we have to compromise with giving up on parallelising tests to allow each one of them to report any logs on failure.

chore(win): enrich logs

---

src/linux/py_proc.h
src/mac/py_proc.h
src/py_proc.c
src/py_proc.h
src/win/py_proc.h

With the removal of the heap scanning logic, we no longer need to keep track of VM bounds so we remove the relevant code.

chore: remove VM bounds tracking logic

---

ChangeLog
src/py_proc.c

We make sure that threads are resumed regardless of potential errors during the sampling of the threads.
Fill out the template below. Any pull request that does not include enough
information to be reviewed in a timely manner may be closed at the maintainers'
discretion.

fix(austinp): ensure threads are resumed on sampling errors

---

ChangeLog
src/austin.c
src/py_proc.c
src/py_proc.h

When Austin is given a command to launch, we make sure that any termination signal that Austin receives is propagated to the spawned process to prevent it from running potentially indefinitely in the background.
We don't expect any tools based on Austin to rely on the previous behaviour, so we do not expect any regressions.
This bug was caught with the austin-python test suite.

fix: propagate signals to spawned process

---

src/linux/py_proc.h

A segmentation fault was caught in CI exposing a missing NULL check on a local variable in recently-added code. We add a check to prevent this from happening.

chore(linux): guard against potentially null map

---

ChangeLog
README.md
scripts/requirements-bm.txt
scripts/requirements-val.txt
src/argparse.c
src/events.h
src/mojo.h
src/py_proc.c
src/py_thread.c
src/py_thread.h
src/python/interp.h
src/version.h
test/functional/test_fork.py
test/requirements.txt

We add support for sub-interpreters. With this change we loop over the linked list of sub-interpreters and sample them in turn. With [PEP 554](https://peps.python.org/pep-0554/) and [PEP 684](https://peps.python.org/pep-0684/), we foresee a potential growing interest into sub-interpreters. Therefore we add support for sub-interpreters to Austin to make it future-proof, at no extra performance cost for the single interpreter scenario.
Extra sub-interpreter identification information is carried by the Stack MOJO event. For the collapsed stack format, we add a prefix to the thread identifier, which represents the sub-interpreter ID. The main interpreter is identified by the 0 ID.
None considered.
None expected
Added an extra test case to verify that we get the extra sub-interpreter …

feat: sub-interpreters support

---

.github/workflows/benchmarks.yml
scripts/benchmark.py
scripts/requirements-bm.txt

We speed up the benchmarks CI run by only running the latest release and dev. Any issues caught in this way can be analysed locally if needed.

ci(benchmarks): run only the last release

---

ChangeLog
configure.ac
snap/snapcraft.yaml
src/austin.h
src/frame.h
test/functional/test_mojo.py

We fix the value of the line end exported in binary MOJO files for samples extracted from CPython < 3.11 and make sure that it is set to 0 to indicate that the information is not available.
Because no issues have been reported that relate to this fix, we assume that nobody was relying on the previous behaviour.
Added a test case to validate that no incorrect location information is emitted from CPython versions prior to 3.11.

fix: line end information for CPython < 3.11

---

ChangeLog
src/linux/common.h
src/linux/py_proc.h
src/py_proc.c

We make use of the /proc/root of the procfs to improve the chances that we can infer the required information, such as the location of the runtime structure and the interpreter version from binaries pointed at by the actual process root. This is relevant for processes running inside containers, since their FS root does not coincide with the host root.
None considered
We are changing the paths that are used to inspect binaries. This might have an impact in the non-containerised cased, albeit the greater generality should ensure that the new code works as intended for a wider range of scenarios. We also bail out early on a failed version inference (in fact, on fatal errors), which _might_ introduce a degree of flakiness in tests.
...

fix(linux): improved container support

---

README.md

There were blue underlines between the badges in README.md, this PR removes them.

doc: fix README underlines between badges

---

src/py_thread.c
src/python/string.h
src/version.h

We remove some old code used for the support of older version of Python that is no longe required.

chore: clean up support for old versions of Python

---

README.md

Aptitude and apt-get are somewhat outdated debian package managers (`aptitude`, uses apt libraries under the hood) or outdated aliases (`apt-get` for `apt`) and I would suggest to use plain `apt`. For this example, apt has the same interface as `apt-get`.

docs: remove reference to aptitude and apt-get

---

.github/workflows/checks.yml
.github/workflows/tests.yml
ChangeLog
README.md
configure.ac
doc/cheatsheet.svg
scripts/build-wheel.py
snap/snapcraft.yaml
src/austin.h
src/py_proc.c
src/py_proc.h
src/py_proc_list.c
src/py_thread.c
src/python/runtime.h
src/version.h
test/__init__.py

We add support for CPython 3.13. This new version introduces a data structure designed for easily exposing the required field offsets to out-of-process tools like Austin, via the ABI. We adapt the coding to allow integrating with this new structure.
We currently limit testing to the CPython 3.13 version with the GIL. No testing has currently been done with either the free-threaded version, nor with the new JIT.
N.A.
There are slim chances that the current approach taken fails under certain circumstances. That is because the new approach would require allocating memory for the Python data structures at runtime, as they are no longer known at compile time. This has been done for some of the more critical structures, but for others we are still relying on the size of the same structures from …

feat: add support for CPython 3.13

---

scripts/build-wheel.py

We improve the wheel script generator by removing the obsolete py2 target and by resolving the image addresses to the absolute raw ones so that images appear as expected in the PyPI page.

ci: improve wheel generation script

---

.github/workflows/release.yml

We make sure that macos binary are built with the expected target platform.
Fixes #242.

ci(release): ensure correct macos target build
